version: '3'

services:
  goapp:
    build: .
    platform: linux/amd64
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - gomysql

  gomysql:
    build: ./data
    platform: linux/amd64
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
